movie/app1/urls.py
from django.urls import path
from .import views
app_name='app1'
urlpatterns = [
    # path('',views.index,name='index'),
    path('',views.MovieList.as_view(),name="index"),


    # path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('movie/<int:pk>',views.MovieDetail.as_view(),name="detail"),

    # path('add/',views.add_movie,name='add_movie'),
    path('add/',views.Movieadd.as_view(),name="add_movie"),

    # path('update/<int:id>/',views.update,name='update'),
    path('update/<int:pk>',views.Movieupdate.as_view(),name="update"),


    # path('delete/<int:id>/', views.delete, name='delete'),
    path('delete/<int:pk>',views.Moviedelete.as_view(),name="delete"),

]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                       document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

movie/app1/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.CharField(max_length=250)
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery',null=True,blank=True)


    def __str__(self):
        return self.name

movie/app1/forms.py
from django import forms
from app1.models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movie/app1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from app1.models import Movie
from app1.forms import MovieForm
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy


# def index(request):
#     movie = Movie.objects.all()
#     context = {
#         'movie_list': movie
#     }
#     return render(request, "index.html", context)
class MovieList(ListView):
    model=Movie
    template_name = "index.html"
    context_object_name = "movie_list"



# def detail(request, movie_id):
#     movie=Movie.objects.get(id=movie_id)
#     return render(request,"detail.html",{'movie':movie})
class MovieDetail(DetailView):
    model=Movie
    template_name = "detail.html"
    context_object_name = "movie"


# def add_movie(request):
#     if request.method=='POST':
#         name=request.POST.get('name')
#         desc=request.POST.get('desc')
#         year=request.POST.get('year')
#         img = request.FILES['img']
#         movie=Movie(name=name,desc=desc,year=year,img=img)
#         movie.save()
#         return redirect("/")
#
#     return render(request,'add.html')

class Movieadd(CreateView):
    model=Movie
    template_name = "add.html"
    fields = '__all__'
    success_url = reverse_lazy('app1:index')






# def update(request,id):
#     movie=Movie.objects.get(id=id)
#     form=MovieForm(instance=movie)
#     if(request.method=="POST"):
#         form = MovieForm(request.POST,request.FILES,instance=movie)
#         if form.is_valid():
#             form.save()
#             return redirect('/')
#     return render(request,'edit.html',{'form':form})

class Movieupdate(UpdateView):
    model = Movie
    template_name = "add.html"
    fields = "__all__"
#     success_url = reverse_lazy('app1:index')
#
#
#
#
#
#
#
# def delete(request,id):
#     if request.method=='POST':
#         movie=Movie.objects.get(id=id)
#         movie.delete()
#         return redirect('/')
#     return render(request,'delete.html')

class Moviedelete(DeleteView):
    model = Movie
    success_url = reverse_lazy('app1:index')
    template_name = "delete.html"

movie/templates/add.html
{% extends 'base.html' %}
{% block body %}
<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    <input type="text" name="name" placeholder="Enter your movie name">-->
<!--    <input type="text" name="desc" placeholder="Enter the movie description">-->
<!--    <input type="text" name="year" placeholder="Enter your movie year">-->
<!--    <input type="file" name="img">-->
<!--    <input type="submit">-->

<!--</form>-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit">

</form>



{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link rel="'stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

      Online Movie Store
  </a>
    <a class="btn btn-success" href="{% url 'app1:add_movie' %}" style="align:center;">ADD MOVIE</a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    <input type="text" name="name" placeholder="Enter your movie name">-->
<!--    <input type="text" name="desc" placeholder="Enter the movie description">-->
<!--    <input type="text" name="year" placeholder="Enter your movie year">-->
<!--    <input type="file" name="img">-->
<!--    <input type="submit">-->

<!--</form>-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Are you sure you want to delete??</p>
    <input type="submit">

</form>



{% endblock %}

movie/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="350">
        </div>
<div class="col-md-6">
    <h4>{{movie.name}}</h4>
    <h6>{{movie.desc}}</h6>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'app1:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'app1:delete' movie.id %}">delete</a>
</div>
    </div>
</div>

{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

{% endblock %}

movie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
      <div class="col-md-3">
          <div class="card" style="margin-right:10px; margin-top:10px; ">
            <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250px;">
            <div class="card-body"  >
                <h5 class="card-title" style="height:50px;" >{{i.name}}</h5>
                <p class="card-text" style="height:70px;">{{i.desc}}</p>
                <a href="{% url 'app1:detail' i.id %}" class="btn btn-primary">Details</a>
            </div>
          </div>
      </div>
        {% endfor %}

    </div>
</div>
{% endblock %}